language: python
matrix:
  allow_failures:
    - os: osx
  include:
    - os: linux
      dist: xenial
      python: "3.5"
      env: TORNADO_VERSION=HH ; WITH_RAVEN=0
    - os: linux
      dist: xenial
      python: "3.5"
      env: TORNADO_VERSION=5.0.2 ; WITH_RAVEN=1
    - os: linux
      dist: xenial
      python: "3.6"
      env: TORNADO_VERSION=HH ; WITH_RAVEN=1
    - os: linux
      dist: xenial
      python: "3.6"
      env: TORNADO_VERSION=5.0.2 ; WITH_RAVEN=0
    - os: linux
      dist: xenial
      python: "3.7"
      env: TORNADO_VERSION=HH ; WITH_RAVEN=1
    - os: linux
      dist: xenial
      python: "3.7"
      env: TORNADO_VERSION=5.0.2 ; WITH_RAVEN=1
    - os: osx
      osx_image: xcode9.4
      language: generic
      env: TORNADO_VERSION=HH ; WITH_RAVEN=1 ; OSX=1
      before_install:
      - brew reinstall openssl
      - pip3 uninstall pycurl
      - pip3 install --install-option="--with-openssl" --install-option="--openssl-dir=/usr/local/opt/openssl" pycurl==7.43.0
install:
  - if [[ $OSX != 1 ]]; then sudo apt-get install libgnutls28-dev libcurl4-gnutls-dev; fi
  - if [[ $TORNADO_VERSION == 'HH' ]]; then pip install https://github.com/hhru/tornado/archive/tornado5.zip; else pip install tornado==$TORNADO_VERSION; fi
  - if [[ $WITH_RAVEN == 1 ]]; then pip install raven; fi
  - python3 setup.py install
script:
  - python3 setup.py test
sudo: required
